### ISSUE TITLE
Agregar meta html tags para Open Graph y Twitter

### ISSUE THREAD

**Issue by Lemin-n** [RustLangES/RustLangES.github.io#17]

**Comment by Lemin-n** [comment]
El PR #32 termina de integrar todas las meta tags para mejorar el SEO como tambien las integraciones con Open Graph y Twitter.

Alguien sugiere algún cambio con respecto a la imagen para OG o la description?

**Comment by SergioRibera** [comment]
El tema del OG ya esta listo me parece? se puede cerrar esta issue?
