### ISSUE TITLE
Contenido desde archivos markdown

### ISSUE THREAD

**Issue by sergiomeneses** [RustLangES/RustLangES.github.io#21]
Estaría mejor si podemos desacoplar los contenidos de la implementación y propongo usar archivos markdown (MD) para tal fin.

**Comment by Phosphorus-M** [comment]
Dejo esto para que tengamos en cuenta
https://github.com/rambip/leptos-markdown

**Comment by SergioRibera** [comment]
Estoy implementando un sistema similar al que usa [Bevy](https://bevyengine.org/asstes) para cuando alguien quiere agregar un asset a la lista de su web, ellos usan `toml` con unos parametros y ya

Aqui pueden ver el repo en el que se agregan nuevas cosas https://github.com/bevyengine/bevy-assets

**Comment by SergioRibera** [comment]
Posiblemente solucionado en #41

**Comment by SergioRibera** [comment]
Cerrando porque al parecer ya se completo
