### ISSUE TITLE
Hacer boton bonito!

### ISSUE THREAD

**Issue by Phosphorus-M** [RustLangES/RustLangES.github.io#24]
Hacer este boton bonito!

Este boton!

![image](https://github.com/RustLangES/RustLangES.github.io/assets/19656993/fa764209-d3d5-49dc-b59b-0f71d47f1cba)

**Comment by Phosphorus-M** [comment]
@michaelcardoza Podrias ayudarnos con esto? :smiley:

**Comment by SergioRibera** [comment]
Ya esta bonito

![image](https://github.com/RustLangES/RustLangES.github.io/assets/56278796/ddfacdb7-029d-4106-9c5f-725372760928)
