### ISSUE TITLE
Validar github workflow

### ISSUE THREAD

**Issue by sergiomeneses** [RustLangES/RustLangES.github.io#3]

**Comment by SergioRibera** [comment]
En este caso, que se necesita validar? O que tipo de github workflows se necesitan?

**Comment by Phosphorus-M** [comment]
Quizas agregar más validaciones con Clippy

**Comment by sergiomeneses** [comment]
Actualmente no existe el paso de verifit del formateo del código  (clippy y fmt) por otro lado teniendo en cuenta que es basado el leptos, existe el proyecto leptosfmt (no tengo claro si es una extensión únicamente para vscode o es posible usarlo en el ci/cd)

**Comment by Phosphorus-M** [comment]
Clippy esta agregado, faltaria fmt y leptosfmt, no seria mala idea.

**Comment by SergioRibera** [comment]
Ya fueron agregados, se cierra el issue?

**Comment by SergioRibera** [comment]
Completado
